export const KEEP_ALIVE_CONNECTION_WORKSPACES_MAX = 6;

export const MAX_LIVE_CONNECTION_SESSIONS = 10;

export const KEEP_ALIVE_TOP_LEVEL_PANELS_MAX = 10;

export const KEEP_ALIVE_WORKBENCH_TABS_MAX = 12;

export const KEEP_ALIVE_DETAIL_PANELS_MAX = 8;

export const KEEP_ALIVE_DOCK_PANELS_MAX = 8;

export const KEEP_ALIVE_WASM_PANELS_MAX = 3;

export const KEEP_ALIVE_WEB_PROXY_PANELS_MAX = 3;

export const STREAM_CHANNEL_BUFFER_LIMIT = 2000;

export const CONNECTION_SESSION_HEARTBEAT_MS = 30000;
