repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt
        language: system
        types: [go]
      - id: go-test
        name: go test ./...
        entry: go
        language: system
        args: ["test", "./..."]
        pass_filenames: false
