package oracle

import (
	"context"
	"errors"
	"testing"

	"github.com/charlesng35/shellcn/internal/models"
	"github.com/charlesng35/shellcn/internal/plugin"
	"github.com/charlesng35/shellcn/plugins/shared/sqldb"
)

func TestManifestRegistersAndStaysDirectOnly(t *testing.T) {
	reg := plugin.NewRegistry()
	if err := reg.Register(New()); err != nil {
		t.Fatalf("register Oracle plugin: %v", err)
	}
	m, ok := reg.Manifest(protocolName)
	if !ok {
		t.Fatal("manifest not registered")
	}
	if m.Agent != nil {
		t.Fatal("Oracle must not declare agent transport")
	}
	if len(m.SupportedTransports) != 1 || m.SupportedTransports[0] != plugin.TransportDirect {
		t.Fatalf("unexpected transports: %+v", m.SupportedTransports)
	}
	if !reg.CredentialKindSupportsProtocol(plugin.CredentialDBPassword, protocolName) {
		t.Fatal("database password credential should support Oracle")
	}
	if !reg.CredentialKindSupportsProtocol(plugin.CredentialTLSClientCert, protocolName) {
		t.Fatal("TLS client certificate credential should support Oracle")
	}
}

func TestParseOptionsUsesTLSCredentialAsTCPSAuth(t *testing.T) {
	opts, err := parseOptions(plugin.ConnectConfig{Config: map[string]any{
		"host":                        "oracle.local",
		"service":                     "FREEPDB1",
		"auth":                        authClientCert,
		"_auth_client_cert_id_secret": "pem-material",
	}})
	if err != nil {
		t.Fatalf("parse options: %v", err)
	}
	if !opts.TCPSAuth || opts.Username != "" || opts.Password != "" || opts.ClientCertificate != "pem-material" || opts.TLSMode != "require" {
		t.Fatalf("unexpected credential material: %+v", opts)
	}
}

func TestParseOptionsUsesTLSClientCertificateCredential(t *testing.T) {
	opts, err := parseOptions(plugin.ConnectConfig{Config: map[string]any{
		"host":                   "oracle.local",
		"service":                "FREEPDB1",
		"username":               "SYSTEM",
		"password":               "secret",
		"tls_mode":               "require",
		"_client_cert_id_secret": "pem-material",
	}})
	if err != nil {
		t.Fatalf("parse options: %v", err)
	}
	if opts.TCPSAuth || opts.ClientCertificate != "pem-material" || opts.Username != "SYSTEM" || opts.Password != "secret" {
		t.Fatalf("unexpected credential material: %+v", opts)
	}
}

func TestQuerySafetyStopsBeforeDatabase(t *testing.T) {
	_, err := executeQueryRequest(context.Background(), &Session{opts: optionsData{ReadOnly: true}}, "SYSTEM", sqldb.QueryRequest{Query: "delete from accounts"})
	if !errors.Is(err, plugin.ErrForbidden) {
		t.Fatalf("expected read-only forbidden error, got %v", err)
	}
	_, err = executeQueryRequest(context.Background(), &Session{opts: optionsData{RequireConfirm: true}}, "SYSTEM", sqldb.QueryRequest{Query: "drop table accounts"})
	var confirmErr confirmationError
	if !errors.As(err, &confirmErr) {
		t.Fatalf("expected confirmation error, got %v", err)
	}
	if got := queryAuditResult(err); got != models.AuditDenied {
		t.Fatalf("confirmation should audit as denied, got %s", got)
	}
}

func TestOracleDDLColumnValidation(t *testing.T) {
	col, err := ddlColumn(sqldb.ColumnSpec{Name: "ID", Type: "NUMBER GENERATED BY DEFAULT AS IDENTITY", Primary: true})
	if err != nil {
		t.Fatalf("valid column rejected: %v", err)
	}
	if col != `"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY` {
		t.Fatalf("unexpected column: %q", col)
	}
	if _, err := ddlColumn(sqldb.ColumnSpec{Name: "bad:name", Type: "VARCHAR2(255)"}); err == nil {
		t.Fatal("invalid identifier accepted")
	}
	if _, err := ddlColumn(sqldb.ColumnSpec{Name: "NAME", Type: "VARCHAR2(255); drop table users"}); err == nil {
		t.Fatal("unsafe type accepted")
	}
}

func TestAlterColumnClause(t *testing.T) {
	got, err := alterColumnClause("NAME", "VARCHAR2(120)", false, "'n/a'")
	if err != nil {
		t.Fatalf("alter clause: %v", err)
	}
	if got != `"NAME" VARCHAR2(120) DEFAULT 'n/a' NOT NULL` {
		t.Fatalf("unexpected modify clause: %q", got)
	}
	if got, err := alterColumnClause("NOTE", "CLOB", true, ""); err != nil || got != `"NOTE" CLOB NULL` {
		t.Fatalf("nullable modify clause wrong: %q err=%v", got, err)
	}
	if _, err := alterColumnClause("bad:name", "NUMBER", true, ""); err == nil {
		t.Fatal("invalid identifier accepted")
	}
	if _, err := alterColumnClause("NAME", "VARCHAR2(10); DROP TABLE x", true, ""); err == nil {
		t.Fatal("unsafe type accepted")
	}
	if _, err := alterColumnClause("NAME", "VARCHAR2(10)", true, "1; DROP TABLE x"); err == nil {
		t.Fatal("unsafe default accepted")
	}
}

func TestConstraintClause(t *testing.T) {
	cases := []struct {
		name, kind                       string
		columns                          any
		check, refTable, refColumns, sql string
	}{
		{name: "PK_PEOPLE", kind: "PRIMARY KEY", columns: "ID", sql: `CONSTRAINT "PK_PEOPLE" PRIMARY KEY ("ID")`},
		{name: "UQ_EMAIL", kind: "UNIQUE", columns: []any{"EMAIL", "TENANT"}, sql: `CONSTRAINT "UQ_EMAIL" UNIQUE ("EMAIL", "TENANT")`},
		{name: "CK_AGE", kind: "CHECK", check: "AGE >= 0", sql: `CONSTRAINT "CK_AGE" CHECK (AGE >= 0)`},
		{name: "FK_ORDER", kind: "FOREIGN KEY", columns: "PERSON_ID", refTable: "APP.PEOPLE", refColumns: "ID", sql: `CONSTRAINT "FK_ORDER" FOREIGN KEY ("PERSON_ID") REFERENCES "APP"."PEOPLE" ("ID")`},
		{name: "FK_LOCAL", kind: "FOREIGN KEY", columns: "PID", refTable: "PEOPLE", refColumns: "ID", sql: `CONSTRAINT "FK_LOCAL" FOREIGN KEY ("PID") REFERENCES "PEOPLE" ("ID")`},
	}
	for _, c := range cases {
		got, err := constraintClause(c.name, c.kind, c.columns, c.check, c.refTable, c.refColumns)
		if err != nil {
			t.Fatalf("%s: %v", c.name, err)
		}
		if got != c.sql {
			t.Fatalf("%s: got %q want %q", c.name, got, c.sql)
		}
	}

	if _, err := constraintClause("bad:name", "UNIQUE", "ID", "", "", ""); err == nil {
		t.Fatal("invalid constraint name accepted")
	}
	if _, err := constraintClause("PK", "PRIMARY KEY", "", "", "", ""); err == nil {
		t.Fatal("primary key without columns accepted")
	}
	if _, err := constraintClause("CK", "CHECK", "", "AGE >= 0; DROP TABLE x", "", ""); err == nil {
		t.Fatal("unsafe check expression accepted")
	}
	if _, err := constraintClause("FK", "FOREIGN KEY", "PID", "", "", "ID"); err == nil {
		t.Fatal("foreign key without referenced table accepted")
	}
	if _, err := constraintClause("X", "EXCLUSION", "ID", "", "", ""); err == nil {
		t.Fatal("unsupported constraint type accepted")
	}
}

func TestObjectIDRoundTrip(t *testing.T) {
	id := objectID("SHELLCN_TEST", "PEOPLE")
	owner, name, err := parseObjectID(id)
	if err != nil {
		t.Fatalf("parse object id: %v", err)
	}
	if owner != "SHELLCN_TEST" || name != "PEOPLE" {
		t.Fatalf("unexpected identity: %s %s", owner, name)
	}
	if _, _, err := parseObjectID("APP:BAD:EXTRA"); err == nil {
		t.Fatal("accepted ambiguous object id")
	}
}

func TestRedactRowsMasksConfiguredColumns(t *testing.T) {
	rows := []row{{"id": int64(1), "access_token": "plain", "name": "alice"}}
	redactRows(rows, sqldb.DefaultRedactColumnPatterns())
	if rows[0]["access_token"] != sqldb.RedactedValue || rows[0]["name"] != "alice" {
		t.Fatalf("unexpected row redaction: %#v", rows)
	}
}

func TestStructuralDDLActionsAreWired(t *testing.T) {
	p := New()
	m := p.Manifest()

	routeIDs := map[string]bool{}
	for _, r := range p.Routes() {
		routeIDs[r.ID] = true
	}
	actionByID := map[string]plugin.Action{}
	for _, a := range m.Actions {
		actionByID[a.ID] = a
	}

	want := []string{
		"oracle.schema.create", "oracle.schema.drop",
		"oracle.constraint.add", "oracle.constraint.drop",
		"oracle.table.rename",
		"oracle.column.alter", "oracle.column.rename",
	}
	for _, id := range want {
		a, ok := actionByID[id]
		if !ok {
			t.Fatalf("missing action %q", id)
		}
		if !routeIDs[a.RouteID] {
			t.Fatalf("action %q points at missing route %q", id, a.RouteID)
		}
	}

	// Every action id referenced by a resource's panels/surfaces must resolve to
	// a declared Action, so the new surfaces are not dangling.
	check := func(ids []string, where string) {
		for _, id := range ids {
			if _, ok := actionByID[id]; !ok {
				t.Fatalf("%s references undefined action %q", where, id)
			}
		}
	}
	for _, res := range m.Resources {
		check(res.Actions.Toolbar, res.Kind+" toolbar")
		check(res.Actions.Row, res.Kind+" row")
		check(res.Actions.Detail, res.Kind+" detail")
		for _, tab := range res.Detail.Tabs {
			if tc, ok := tab.Config.(plugin.TableConfig); ok {
				check(tc.ActionIDs, res.Kind+"/"+tab.Key+" actionIds")
				check(tc.RowActionIDs, res.Kind+"/"+tab.Key+" rowActionIds")
			}
		}
	}
}

func TestTableDataGridIsEditable(t *testing.T) {
	p := New()
	m := p.Manifest()
	routeIDs := map[string]bool{}
	for _, r := range p.Routes() {
		routeIDs[r.ID] = true
	}
	var data plugin.Panel
	for _, res := range m.Resources {
		if res.Kind != "table" {
			continue
		}
		for _, tab := range res.Detail.Tabs {
			if tab.Key == "data" {
				data = tab
			}
		}
	}
	tc, ok := data.Config.(plugin.TableConfig)
	if data.Key == "" || !ok || !tc.Editable {
		t.Fatalf("table Data tab must be an editable grid: %#v", data.Config)
	}
	for key, ds := range map[string]*plugin.DataSource{"insert": tc.Insert, "update": tc.Update, "delete": tc.Delete} {
		if ds == nil {
			t.Fatalf("Data tab missing %q mutation source", key)
		}
		if !routeIDs[ds.RouteID] {
			t.Fatalf("Data tab %q points at missing route %q", key, ds.RouteID)
		}
	}
}
