package oracle

import (
	"context"
	"errors"
	"testing"

	"github.com/charlesng35/shellcn/internal/models"
	"github.com/charlesng35/shellcn/internal/plugin"
	"github.com/charlesng35/shellcn/plugins/shared/sqldb"
)

func TestManifestRegistersAndStaysDirectOnly(t *testing.T) {
	reg := plugin.NewRegistry()
	if err := reg.Register(New()); err != nil {
		t.Fatalf("register Oracle plugin: %v", err)
	}
	m, ok := reg.Manifest(protocolName)
	if !ok {
		t.Fatal("manifest not registered")
	}
	if m.Agent != nil {
		t.Fatal("Oracle must not declare agent transport")
	}
	if len(m.SupportedTransports) != 1 || m.SupportedTransports[0] != plugin.TransportDirect {
		t.Fatalf("unexpected transports: %+v", m.SupportedTransports)
	}
	if !reg.CredentialKindSupportsProtocol(plugin.CredentialDBPassword, protocolName) {
		t.Fatal("database password credential should support Oracle")
	}
	if !reg.CredentialKindSupportsProtocol(plugin.CredentialTLSClientCert, protocolName) {
		t.Fatal("TLS client certificate credential should support Oracle")
	}
}

func TestParseOptionsUsesTLSCredentialAsTCPSAuth(t *testing.T) {
	opts, err := parseOptions(plugin.ConnectConfig{Config: map[string]any{
		"host":                        "oracle.local",
		"service":                     "FREEPDB1",
		"auth":                        authClientCert,
		"_auth_client_cert_id_secret": "pem-material",
	}})
	if err != nil {
		t.Fatalf("parse options: %v", err)
	}
	if !opts.TCPSAuth || opts.Username != "" || opts.Password != "" || opts.ClientCertificate != "pem-material" || opts.TLSMode != "require" {
		t.Fatalf("unexpected credential material: %+v", opts)
	}
}

func TestParseOptionsUsesTLSClientCertificateCredential(t *testing.T) {
	opts, err := parseOptions(plugin.ConnectConfig{Config: map[string]any{
		"host":                   "oracle.local",
		"service":                "FREEPDB1",
		"username":               "SYSTEM",
		"password":               "secret",
		"tls_mode":               "require",
		"_client_cert_id_secret": "pem-material",
	}})
	if err != nil {
		t.Fatalf("parse options: %v", err)
	}
	if opts.TCPSAuth || opts.ClientCertificate != "pem-material" || opts.Username != "SYSTEM" || opts.Password != "secret" {
		t.Fatalf("unexpected credential material: %+v", opts)
	}
}

func TestQuerySafetyStopsBeforeDatabase(t *testing.T) {
	_, err := executeQueryRequest(context.Background(), &Session{opts: optionsData{ReadOnly: true}}, "SYSTEM", sqldb.QueryRequest{Query: "delete from accounts"})
	if !errors.Is(err, plugin.ErrForbidden) {
		t.Fatalf("expected read-only forbidden error, got %v", err)
	}
	_, err = executeQueryRequest(context.Background(), &Session{opts: optionsData{RequireConfirm: true}}, "SYSTEM", sqldb.QueryRequest{Query: "drop table accounts"})
	var confirmErr confirmationError
	if !errors.As(err, &confirmErr) {
		t.Fatalf("expected confirmation error, got %v", err)
	}
	if got := queryAuditResult(err); got != models.AuditDenied {
		t.Fatalf("confirmation should audit as denied, got %s", got)
	}
}

func TestOracleDDLColumnValidation(t *testing.T) {
	col, err := ddlColumn(sqldb.ColumnSpec{Name: "ID", Type: "NUMBER GENERATED BY DEFAULT AS IDENTITY", Primary: true})
	if err != nil {
		t.Fatalf("valid column rejected: %v", err)
	}
	if col != `"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY` {
		t.Fatalf("unexpected column: %q", col)
	}
	if _, err := ddlColumn(sqldb.ColumnSpec{Name: "bad:name", Type: "VARCHAR2(255)"}); err == nil {
		t.Fatal("invalid identifier accepted")
	}
	if _, err := ddlColumn(sqldb.ColumnSpec{Name: "NAME", Type: "VARCHAR2(255); drop table users"}); err == nil {
		t.Fatal("unsafe type accepted")
	}
}

func TestObjectIDRoundTrip(t *testing.T) {
	id := objectID("SHELLCN_TEST", "PEOPLE")
	owner, name, err := parseObjectID(id)
	if err != nil {
		t.Fatalf("parse object id: %v", err)
	}
	if owner != "SHELLCN_TEST" || name != "PEOPLE" {
		t.Fatalf("unexpected identity: %s %s", owner, name)
	}
	if _, _, err := parseObjectID("APP:BAD:EXTRA"); err == nil {
		t.Fatal("accepted ambiguous object id")
	}
}

func TestRedactRowsMasksConfiguredColumns(t *testing.T) {
	rows := []row{{"id": int64(1), "access_token": "plain", "name": "alice"}}
	redactRows(rows, sqldb.DefaultRedactColumnPatterns())
	if rows[0]["access_token"] != sqldb.RedactedValue || rows[0]["name"] != "alice" {
		t.Fatalf("unexpected row redaction: %#v", rows)
	}
}

func TestTableDataGridIsEditable(t *testing.T) {
	p := New()
	m := p.Manifest()
	routeIDs := map[string]bool{}
	for _, r := range p.Routes() {
		routeIDs[r.ID] = true
	}
	var data plugin.Tab
	for _, res := range m.Resources {
		if res.Kind != "table" {
			continue
		}
		for _, tab := range res.Detail.Tabs {
			if tab.Key == "data" {
				data = tab
			}
		}
	}
	if data.Key == "" || data.Config["editable"] != true {
		t.Fatalf("table Data tab must be an editable grid: %#v", data.Config)
	}
	for _, key := range []string{"insert", "update", "delete"} {
		ds, ok := data.Config[key].(*plugin.DataSource)
		if !ok {
			t.Fatalf("Data tab missing %q mutation source", key)
		}
		if !routeIDs[ds.RouteID] {
			t.Fatalf("Data tab %q points at missing route %q", key, ds.RouteID)
		}
	}
}
