import type { Component } from "vue";
import {
  Activity,
  Box,
  Boxes,
  Braces,
  Camera,
  Cable,
  ChevronDown,
  ChevronRight,
  Circle,
  Cloud,
  CloudCog,
  Code2,
  Container,
  Copy,
  Cpu,
  Database,
  Download,
  DownloadCloud,
  EllipsisVertical,
  Eye,
  EyeOff,
  File,
  FileText,
  Folder,
  FolderOpen,
  FolderPlus,
  Globe,
  HardDrive,
  Info,
  KeyRound,
  Layers,
  LayoutGrid,
  List,
  Lock,
  LogOut,
  MemoryStick,
  Monitor,
  Network,
  Package,
  PackageOpen,
  Pencil,
  Play,
  Plug,
  Plus,
  Power,
  PowerOff,
  RefreshCw,
  RotateCw,
  Route,
  Save,
  Search,
  Send,
  Server,
  Share2,
  Shield,
  ShieldAlert,
  Ship,
  SlidersHorizontal,
  Square,
  ScrollText,
  Table,
  Terminal,
  Trash2,
  TriangleAlert,
  Unplug,
  Upload,
  UploadCloud,
  User,
  Users,
  Video,
  Wrench,
  Workflow,
  X,
} from "@lucide/vue";

export const FALLBACK_ICON = "circle";

export const iconComponents: Record<string, Component> = {
  alert: TriangleAlert,
  api: Send,
  box: Box,
  boxes: Boxes,
  braces: Braces,
  camera: Camera,
  cable: Cable,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  circle: Circle,
  cloud: Cloud,
  "cloud-cog": CloudCog,
  code: Code2,
  compose: Boxes,
  container: Container,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  db: Database,
  desktop: Monitor,
  disk: HardDrive,
  docker: Ship,
  download: Download,
  "download-cloud": DownloadCloud,
  "ellipsis-vertical": EllipsisVertical,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-text": FileText,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  globe: Globe,
  grid: LayoutGrid,
  "hard-drive": HardDrive,
  info: Info,
  key: KeyRound,
  layers: Layers,
  list: List,
  lock: Lock,
  logs: List,
  "log-out": LogOut,
  memory: MemoryStick,
  monitor: Monitor,
  metrics: Activity,
  network: Network,
  package: Package,
  "package-open": PackageOpen,
  pencil: Pencil,
  play: Play,
  plug: Plug,
  plus: Plus,
  power: Power,
  "power-off": PowerOff,
  refresh: RefreshCw,
  "refresh-cw": RefreshCw,
  restart: RotateCw,
  "rotate-cw": RotateCw,
  route: Route,
  save: Save,
  scroll: ScrollText,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  server: Server,
  settings: SlidersHorizontal,
  share: Share2,
  "share-2": Share2,
  shield: Shield,
  "shield-alert": ShieldAlert,
  ship: Ship,
  stop: Square,
  table: Table,
  terminal: Terminal,
  trash: Trash2,
  unplug: Unplug,
  upload: Upload,
  "upload-cloud": UploadCloud,
  user: User,
  users: Users,
  video: Video,
  volume: HardDrive,
  wrench: Wrench,
  workflow: Workflow,
  x: X,
};

export const appIconNames = Object.keys(iconComponents).sort();
