import type { Component } from "vue";
import {
  Activity,
  Box,
  Camera,
  ChevronDown,
  ChevronRight,
  Circle,
  TriangleAlert,
  Code2,
  Copy,
  Database,
  Download,
  EllipsisVertical,
  Folder,
  FolderOpen,
  FolderPlus,
  Globe,
  Info,
  KeyRound,
  Layers,
  LayoutGrid,
  List,
  Lock,
  LogOut,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Search,
  Server,
  Share2,
  SlidersHorizontal,
  Square,
  Terminal,
  Trash2,
  Upload,
  User,
  Users,
  Video,
  Workflow,
  X,
} from "@lucide/vue";

export const FALLBACK_ICON = "circle";

export const iconComponents: Record<string, Component> = {
  alert: TriangleAlert,
  box: Box,
  camera: Camera,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  circle: Circle,
  code: Code2,
  copy: Copy,
  database: Database,
  db: Database,
  download: Download,
  "ellipsis-vertical": EllipsisVertical,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  globe: Globe,
  grid: LayoutGrid,
  info: Info,
  key: KeyRound,
  layers: Layers,
  list: List,
  lock: Lock,
  logs: List,
  "log-out": LogOut,
  metrics: Activity,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  "refresh-cw": RefreshCw,
  search: Search,
  server: Server,
  settings: SlidersHorizontal,
  share: Share2,
  "share-2": Share2,
  stop: Square,
  terminal: Terminal,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  video: Video,
  workflow: Workflow,
  x: X,
};

export const appIconNames = Object.keys(iconComponents).sort();
