name: CI

on:
  push:
    branches:
      - main
      - core-modules
  pull_request:

env:
  GOTOOLCHAIN: auto

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Verify formatting
        run: |
          fmt_out=$(gofmt -l .)
          if [ -n "$fmt_out" ]; then
            echo "Go files need formatting:"
            echo "$fmt_out"
            exit 1
          fi

      - name: Run tests
        env:
          GOCACHE: ${{ github.workspace }}/.cache/go-build
        run: go test ./...
